#!/bin/bash

stowsh=../../stowsh

fail=0
mkdir -p "uninstalled"
rm -rf "dest"
cp -r "uninstalled" "dest"
$stowsh -vv -t "dest" "pkg"
diff -qr "dest" "installed" || fail=1
$stowsh -vv -D -t "dest" "pkg"
diff -qr "dest" "uninstalled" || fail=1
if [[ $fail == 1 ]] ; then
    echo "FAIL"
    exit 1
else
    echo "OK"
    rm -rf "dest"
    exit 0
fi
